/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as ProfessorsRouteImport } from './routes/professors'
import { Route as DevelopmentRouteImport } from './routes/development'
import { Route as CoachingRouteImport } from './routes/coaching'
import { Route as BookRouteImport } from './routes/book'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicBookingRequestRouteImport } from './routes/api/public/booking-request'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorsRoute = ProfessorsRouteImport.update({
  id: '/professors',
  path: '/professors',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopmentRoute = DevelopmentRouteImport.update({
  id: '/development',
  path: '/development',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachingRoute = CoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBookingRequestRoute = ApiPublicBookingRequestRouteImport.update({
  id: '/api/public/booking-request',
  path: '/api/public/booking-request',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/coaching': typeof CoachingRoute
  '/development': typeof DevelopmentRoute
  '/professors': typeof ProfessorsRoute
  '/testimonials': typeof TestimonialsRoute
  '/api/public/booking-request': typeof ApiPublicBookingRequestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/coaching': typeof CoachingRoute
  '/development': typeof DevelopmentRoute
  '/professors': typeof ProfessorsRoute
  '/testimonials': typeof TestimonialsRoute
  '/api/public/booking-request': typeof ApiPublicBookingRequestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book': typeof BookRoute
  '/coaching': typeof CoachingRoute
  '/development': typeof DevelopmentRoute
  '/professors': typeof ProfessorsRoute
  '/testimonials': typeof TestimonialsRoute
  '/api/public/booking-request': typeof ApiPublicBookingRequestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book'
    | '/coaching'
    | '/development'
    | '/professors'
    | '/testimonials'
    | '/api/public/booking-request'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book'
    | '/coaching'
    | '/development'
    | '/professors'
    | '/testimonials'
    | '/api/public/booking-request'
  id:
    | '__root__'
    | '/'
    | '/book'
    | '/coaching'
    | '/development'
    | '/professors'
    | '/testimonials'
    | '/api/public/booking-request'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookRoute: typeof BookRoute
  CoachingRoute: typeof CoachingRoute
  DevelopmentRoute: typeof DevelopmentRoute
  ProfessorsRoute: typeof ProfessorsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  ApiPublicBookingRequestRoute: typeof ApiPublicBookingRequestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professors': {
      id: '/professors'
      path: '/professors'
      fullPath: '/professors'
      preLoaderRoute: typeof ProfessorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/development': {
      id: '/development'
      path: '/development'
      fullPath: '/development'
      preLoaderRoute: typeof DevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaching': {
      id: '/coaching'
      path: '/coaching'
      fullPath: '/coaching'
      preLoaderRoute: typeof CoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/booking-request': {
      id: '/api/public/booking-request'
      path: '/api/public/booking-request'
      fullPath: '/api/public/booking-request'
      preLoaderRoute: typeof ApiPublicBookingRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookRoute: BookRoute,
  CoachingRoute: CoachingRoute,
  DevelopmentRoute: DevelopmentRoute,
  ProfessorsRoute: ProfessorsRoute,
  TestimonialsRoute: TestimonialsRoute,
  ApiPublicBookingRequestRoute: ApiPublicBookingRequestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
